function assert_gdsii_toolbox_ready()
%ASSERT_GDSII_TOOLBOX_READY Ensure GDSII Toolbox and its MEX files are ready.

required_functions = { ...
    'gds_element', ...
    'gds_structure', ...
    'gds_library', ...
    'write_gds_library' ...
    };

is_missing_function = cellfun(@(name) isempty(which(name)), required_functions);
missing_functions = required_functions(is_missing_function);

if ~isempty(missing_functions)
    error('assert_gdsii_toolbox_ready:ToolboxMissing', [ ...
        'Missing GDSII Toolbox functions: %s\n' ...
        'Add the toolbox root with addpath(genpath(...)) before running this script.' ...
        ], strjoin(missing_functions, ', '));
end

gds_element_path = which('gds_element');
toolbox_root = fileparts(fileparts(fileparts(gds_element_path)));
required_mex = { ...
    fullfile(toolbox_root, 'Basic', '@gds_element', 'private', ['new_internal.' mexext]), ...
    fullfile(toolbox_root, 'Basic', '@gds_element', 'private', ['get_element_data.' mexext]), ...
    fullfile(toolbox_root, 'Basic', '@gds_element', 'private', ['set_element_data.' mexext]), ...
    fullfile(toolbox_root, 'Basic', 'gdsio', ['gds_beginlib.' mexext]), ...
    fullfile(toolbox_root, 'Basic', 'gdsio', ['gds_endlib.' mexext]), ...
    fullfile(toolbox_root, 'Basic', 'gdsio', ['gds_beginstruct.' mexext]), ...
    fullfile(toolbox_root, 'Basic', 'gdsio', ['gds_endstruct.' mexext]), ...
    fullfile(toolbox_root, 'Basic', 'gdsio', ['gds_write_element.' mexext]) ...
    };

is_missing_mex = ~cellfun(@(path_name) exist(path_name, 'file') == 3, required_mex);
missing_mex = required_mex(is_missing_mex);

if ~isempty(missing_mex)
    error('assert_gdsii_toolbox_ready:ToolboxIncomplete', [ ...
        'GDSII Toolbox was found, but required MEX files are missing: %s\n' ...
        'Run mex -setup C, mex -setup C++, then run makemex in the toolbox root.' ...
        ], strjoin(missing_mex, ', '));
end
end
