function cell_struct = build_basic_cell(params, layers)
%BUILD_BASIC_CELL Build a single parameterized layout cell with GDSII Toolbox.

assert_gdsii_toolbox_ready();
params = validate_params(params);
layers = validate_layers(layers);

cell_struct = gds_structure(normalize_cell_name(params.cell_name));

body_xy = rectangle_polygon([0.0, 0.0], params.body_w_um, params.body_h_um);
cell_struct(end + 1) = gds_element( ...
    'boundary', ...
    'xy', body_xy, ...
    'layer', layers.main.layer, ...
    'dtype', layers.main.datatype);

if params.marker_size_um > 0
    marker_xy = rectangle_polygon( ...
        params.marker_offset_um, ...
        params.marker_size_um, ...
        params.marker_size_um);

    cell_struct(end + 1) = gds_element( ...
        'boundary', ...
        'xy', marker_xy, ...
        'layer', layers.marker.layer, ...
        'dtype', layers.marker.datatype);
end

if params.add_label
    label_element = create_label_element(params, layers);
    if ~isempty(label_element)
        cell_struct(end + 1) = label_element;
    end
end
end

function params = validate_params(params)
required_fields = { ...
    'cell_name', ...
    'unit_um', ...
    'body_w_um', ...
    'body_h_um', ...
    'marker_size_um', ...
    'out_gds' ...
    };

for k = 1:numel(required_fields)
    field_name = required_fields{k};
    if ~isfield(params, field_name)
        error('build_basic_cell:MissingField', ...
            'Missing required parameter field "%s".', field_name);
    end
end

if ~isfield(params, 'marker_offset_um')
    params.marker_offset_um = [ ...
        0.5 * params.body_w_um + params.marker_size_um, ...
        0.5 * params.body_h_um + params.marker_size_um ...
        ];
end

if ~isfield(params, 'add_label')
    params.add_label = false;
end

validateattributes(params.cell_name, {'char', 'string'}, {'nonempty'}, ...
    mfilename, 'params.cell_name');
validateattributes(params.unit_um, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'positive'}, mfilename, 'params.unit_um');
validateattributes(params.body_w_um, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'positive'}, mfilename, 'params.body_w_um');
validateattributes(params.body_h_um, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'positive'}, mfilename, 'params.body_h_um');
validateattributes(params.marker_size_um, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'nonnegative'}, ...
    mfilename, 'params.marker_size_um');
validateattributes(params.marker_offset_um, {'numeric'}, ...
    {'real', 'finite', 'vector', 'numel', 2}, ...
    mfilename, 'params.marker_offset_um');
validateattributes(params.add_label, {'logical', 'numeric'}, ...
    {'scalar'}, mfilename, 'params.add_label');
validateattributes(params.out_gds, {'char', 'string'}, {'nonempty'}, ...
    mfilename, 'params.out_gds');
end

function layers = validate_layers(layers)
required_groups = {'main', 'marker', 'label'};

for k = 1:numel(required_groups)
    group_name = required_groups{k};
    if ~isfield(layers, group_name)
        error('build_basic_cell:MissingLayerGroup', ...
            'Missing layer group "%s".', group_name);
    end
end

validate_layer_pair(layers.main, 'layers.main');
validate_layer_pair(layers.marker, 'layers.marker');

if ~isfield(layers.label, 'layer') || ~isfield(layers.label, 'texttype')
    error('build_basic_cell:MissingLayerField', ...
        'layers.label must contain "layer" and "texttype".');
end

validateattributes(layers.label.layer, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', '>=', 0, '<=', 255}, ...
    mfilename, 'layers.label.layer');
validateattributes(layers.label.texttype, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', '>=', 0, '<=', 255}, ...
    mfilename, 'layers.label.texttype');
end

function validate_layer_pair(layer_group, argument_name)
if ~isfield(layer_group, 'layer') || ~isfield(layer_group, 'datatype')
    error('build_basic_cell:MissingLayerField', ...
        '%s must contain "layer" and "datatype".', argument_name);
end

validateattributes(layer_group.layer, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', '>=', 0, '<=', 255}, ...
    mfilename, [argument_name '.layer']);
validateattributes(layer_group.datatype, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', '>=', 0, '<=', 255}, ...
    mfilename, [argument_name '.datatype']);
end

function polygon_xy = rectangle_polygon(center_xy, width_um, height_um)
half_width = width_um / 2.0;
half_height = height_um / 2.0;

x0 = center_xy(1) - half_width;
x1 = center_xy(1) + half_width;
y0 = center_xy(2) - half_height;
y1 = center_xy(2) + half_height;

polygon_xy = [ ...
    x0, y0; ...
    x0, y1; ...
    x1, y1; ...
    x1, y0; ...
    x0, y0 ...
    ];
end

function cell_name = normalize_cell_name(raw_name)
cell_name = char(string(raw_name));
cell_name = regexprep(strtrim(cell_name), '\s+', '_');
cell_name = regexprep(cell_name, '[^A-Za-z0-9_]', '_');

if isempty(cell_name)
    error('build_basic_cell:InvalidCellName', ...
        'Cell name must contain at least one valid character.');
end
end

function element = create_label_element(params, layers)
label_xy = [0.0, -0.5 * params.body_h_um - 1.5 * max(params.marker_size_um, 1.0)];

try
    element = gds_element( ...
        'text', ...
        'xy', label_xy, ...
        'layer', layers.label.layer, ...
        'texttype', layers.label.texttype, ...
        'string', normalize_cell_name(params.cell_name));
catch label_error
    warning('build_basic_cell:LabelSkipped', ...
        ['Label creation failed with the current toolbox API (%s). ' ...
        'Continuing without a text label.'], label_error.message);
    element = [];
end
end
